dotenv: .env
networks:
  mainnet:
    weth: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    uni_router: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
    uni_factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
    WEB3_INFURA_URL: 'https://mainnet.infura.io/v3/YOUR_INFURA_ID'
  rinkeby:
    weth: '0xc778417e063141139fce010982780140aa0cd5ab'
    test_token: #test_token_address
    uni_router: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
    uni_factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
    WEB3_INFURA_URL: 'https://rinkeby.infura.io/v3/YOUR_INFURA_ID'
wallets:
  from_key: ${PRIVATE_KEY}
  from_key2: ${PRIVATE_KEY2}
